name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  html:
    name: validate html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Ensure xmllint
        run: xmllint --version || (sudo apt-get update && sudo apt-get install -y libxml2-utils)
      - name: Validate index.html
        run: xmllint --html --noout index.html
